name: Trivy vulnerability scanner
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24.9
      
      - name: Build an image from Dockerfile
        run: |
          export REGISTRY=test
          export DOCKER_CLI_EXPERIMENTAL=enabled
          export OUTPUT_TYPE=docker
          make build-container-linux-amd64
          make build-container-linux-arm64

      - name: Save Docker image to tar
        run: |
          docker ps
          docker images          
          docker save test/local-volume-provisioner:latest_linux_amd64 -o local-volume-provisioner_latest_linux_amd64.tar
          docker save test/local-volume-provisioner:latest_linux_arm64 -o local-volume-provisioner_latest_linux_arm64.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: local-volume-provisioner-image-linux-amd64
          path: local-volume-provisioner_latest_linux_amd64.tar
          if-no-files-found: error
          retention-days: 7

      - name: Upload Docker image artifact (arm64)
        uses: actions/upload-artifact@v4
        with:
          name: local-volume-provisioner-image-linux-arm64
          path: local-volume-provisioner_latest_linux_arm64.tar
          if-no-files-found: error
          retention-days: 7

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        env:
          TRIVY_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-db:2"
        with:
          image-ref: 'test/local-volume-provisioner:latest_linux_amd64'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'

      - name: Run Trivy vulnerability scanner (arm64)
        uses: aquasecurity/trivy-action@master
        env:
          TRIVY_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-db:2"
        with:
          image-ref: 'test/local-volume-provisioner:latest_linux_arm64'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'

